### ISSUE TITLE
Error: Multiple mates found for read

### ISSUE THREAD

**Issue by bharatij** [bahlolab/Bio-STR-exSTRa#21]
Hi Rick,
I am analyzing bwa -mem (version 0.7.13) generated, sorted and Mark duplicate bam files with perl module. I get the following error at one locus and then the program exits.

"Error: Multiple mates found for read"

I was wondering if there is any way to exclude such read (with multiple mate)  if it is problematic and continue with the rest of read and locus processing.
Thanks,
Bharati

**Comment by trickytank** [comment]
Hi Bharati, 

Can I ask where these files were generated? I've only encountered this problem with simulated data where sequence identifiers were not unique; in that case it was important for my colleague to correct their simulation since mates could be matched incorrectly.

You have the choice of ignoring this read, or just using the first mate found for that read (probably the first read to appear in the BAM file, but I'm not 100% sure on this).

Edit the file https://github.com/bahlolab/Bio-STR-exSTRa/blob/master/lib/Bio/STR/exSTRa.pm line 1514 as follows. 

To ignore this read, replace with:
`
            warn "Error: Multiple mates found for read " . $read1->name . "\n";
            return undef;
`

Alternatively, to use the first read found, replace with:

`
            warn "Error: Multiple mates found for read " . $read1->name . "\n";
            return $reads2[0]; 
`

I may consider making this a command line option in the future if it appears this is coming from real data.

**Comment by bharatij** [comment]
Hi Rick,
Thank for your help.  I am analyzing whole exome data. 
I made the change at line 1514 and chose the second option to use the first read found and now it is running fine. 
Thanks,
Bharati

**Comment by Avichair** [comment]
Hello. 
I'm working on exome data. I tried to use this module and encountered the same problem mentioned above. I've tried to edit the file exSTRa.pm but for some reason I still got the same error.

I'll be thankful for your help.

**Comment by Avichair** [comment]
I've found a solution. After the editing of the file, I ran again the building process of the module and now its working.
Thank you.

**Comment by Jolleboll** [comment]
Hello. I too get this error when using actual data. Perhaps 80 % of my bams terminate for this error. Very odd. Some are exomes, some are genomes.

**Comment by trickytank** [comment]
A potential fix for this is in the pull request #26

**Comment by trickytank** [comment]
This is probably fixed now in the release.
