### ISSUE TITLE
Repeat expansion loci for hg38

### ISSUE THREAD

**Issue by hchetia** [bahlolab/Bio-STR-exSTRa#25]
Hi,
When will repeat expansion loci for hg38 for exSTRa be available?
Can Repeat Catalog generated by Illumina for hg38 be used with this tool?

best
hasna

**Comment by trickytank** [comment]
Hi,

This is available in the latest exSTRa release. See
https://github.com/bahlolab/exSTRa/tree/master/inst/extdata for the repeat
loci for hg38.

I'm not sure about the repeat catalog by Illuminia can be used as is, since
we made it to either use our format (column order not important) or from
the UCSC Simple Repeats track download.

Regards,
Rick
